server:
  port: 8765

spring:
  application:
    name: apiGateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      preferIpAddress: true
management:
  endpoint:
    gateway:
      enabled: true

