server:
  port: 8089
spring:
  application:
    name: userservice
  datasource:
    url: jdbc:mysql://localhost:3306/userdb?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrival=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  kafka:
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      group-id: groupone
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
jwt:
  secret:
    key: testsecretkey
management:
  endpoint:
    gateway:
      enabled: true


